### ISSUE TITLE
config to delete closed PR

### ISSUE THREAD

**Issue by cyberhck** [SvanBoxel/delete-merged-branch#106]
https://github.com/SvanBoxel/delete-merged-branch/blob/ecb075b8a034687a78aeb55515d553ece81c0d8e/lib/delete-merged-branch.js#L21-L24

I think yml file should allow a config which will also delete a branch if it's closed.

**Comment by cyberhck** [comment]
I'm willing to provide a PR for this if you're interested :)

**Comment by SvanBoxel** [comment]
Go ahead @cyberhck
