### ISSUE TITLE
hey your NPM_TOKEN is invalid

### ISSUE THREAD

**Issue by cyberhck** [SvanBoxel/delete-merged-branch#116]
I think you reset the tokens so semantic-release is failing, do you mind setting it up again? Thanks.

**Comment by cyberhck** [comment]
@SvanBoxel  did you notice this yet?

**Comment by cyberhck** [comment]
@SvanBoxel tagging one more time :)

**Comment by SvanBoxel** [comment]
Hi @cyberhck, I'm on it. :)

**Comment by cyberhck** [comment]
hey, once it's done, can you trigger a release?

**Comment by SvanBoxel** [comment]
Fixed with https://github.com/SvanBoxel/delete-merged-branch/issues/122
