### ISSUE TITLE
This feature already exists

### ISSUE THREAD

**Issue by cmardonespino** [SvanBoxel/delete-merged-branch#147]
Hello amigos,

Im just wondering if is necessary to continue working on this project if this feature already exists :/ You can find it on repository configuration

<img width="1011" alt="Screen Shot 2019-11-24 at 01 15 40" src="https://user-images.githubusercontent.com/23668723/69489545-66a19d80-0e58-11ea-82c2-ee9f7cff8899.png">

Probably this action could be better if you offer more features that github currently gives

**Comment by SvanBoxel** [comment]
That’s described in the readme as well. This app does still give you some features you don’t get natively.
