### ISSUE TITLE
Delete branches on forks too

### ISSUE THREAD

**Issue by ctrom** [SvanBoxel/delete-merged-branch#20]
Is it possible to have branches that are merged from forks automatically deleted?

**Comment by SvanBoxel** [comment]
Hi @ctrom 👋 

You cannot grant GitHub apps access to other repositories besides the repository where the app is installed. So no, unfortunately, this isn't possible.

**Comment by ctrom** [comment]
@SvanBoxel That's unfortunate. Thanks for the response though!
