### ISSUE TITLE
master branch getting deleted

### ISSUE THREAD

**Issue by ctrom** [SvanBoxel/delete-merged-branch#21]
Since installing this plugin, we've been having issues with our master branches getting deleted. 

Example Scenario:

1. Repository has its default branch set to `master`.
2. User1 makes a PR from their fork (User1 wants to merge 1 commit into `OrgName:master` from `User1:master`).
3. PR gets merged.
4. `OrgName:master` branch is deleted and the default branch is set to one of the other branches on the repository.

Our testing indicates that this issue does not occur if the PR is from a non-master fork branch (User1 wants to merge 1 commit into `OrgName:master` from `User1:NewFeatureBranch`).

**Comment by SvanBoxel** [comment]
Although people threat branches names `master` in a special way, from a git point-of-view it's just a normal branch. Have you looked into [Protected branches](https://help.github.com/articles/about-protected-branches/)? That should prevent this problem.

**Comment by ctrom** [comment]
Perhaps I'm misunderstanding how this tool is supposed to work. If `User1:master` is getting merged into `OrgName:master`, I would think we would want to keep `OrgName:master` around (since we just merged into it). If we were merging `OrgName:master` into `OrgName:ReleaseBranch`, I can understand deleting `master` because we've just updated another branch to contain master's changes, but that isn't what we're experiencing.

**Comment by SvanBoxel** [comment]
You're right @ctrom, this sounds like a bug. Let me try to reproduce it. Also, feel free to submit a PR. 👍

**Comment by SvanBoxel** [comment]
Hey @ctrom, I just released a new version that includes this bug fix.

**Comment by ctrom** [comment]
@SvanBoxel Awesome, thanks for getting this fixed so fast.
