### ISSUE TITLE
Only delete on certain base branches

### ISSUE THREAD

**Issue by seeplusplus** [SvanBoxel/delete-merged-branch#225]
We can currently exclude based on the head branch of a PR. We want to be able to choose to only delete head on branches that are merged to a given base branch. An example would be the following
```
on_base:
  - main
  - qa
```

This would act as a whitelist, so if a PR targets dev, it would not cause the source branch to be deleted.

I'm working on adding this now, just opening the issue to have a number.

**Comment by SvanBoxel** [comment]
Great suggestion @seeplusplus 

> I'm working on adding this now, just opening the issue to have a number.

And thank you very much. Looking forward to the PR.

**Comment by seeplusplus** [comment]
@SvanBoxel pinging you bc the PR's been open for 16 days. I see your status is slow to respond, but just making sure you saw the PR is open :)

**Comment by SvanBoxel** [comment]
You're right and did great work! Approved and merged. Thank you @seeplusplus 🙇🏽

**Comment by seeplusplus** [comment]
@SvanBoxel looks like the build failed for this PR

https://github.com/SvanBoxel/delete-merged-branch/runs/4997779425?check_suite_focus=true#step:6:47

Anything I can do to help with this?
