### ISSUE TITLE
Upgrade Action to use node 16 instead of node 12

### ISSUE THREAD

**Issue by zangbe** [SvanBoxel/delete-merged-branch#248]
Following the recent blog post ["GitHub Actions: All Actions will begin running on Node16 instead of Node12"](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) by GitHub, I noticed this action is still running on `node12`:

`action.yml`
```
runs:
  using: 'node12'
  main: 'dist/index.js'
```

This is the warning I see every time I my workflow:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: SvanBoxel/delete-merged-branch@1.4.2
```

**Comment by SvanBoxel** [comment]
I agree. If you want to you can open a PR that addresses this @zangbe. Big thanks.
