### ISSUE TITLE
If I want to exempt certain branches like 'release' or 'development' from this, is that possible?

### ISSUE THREAD

**Issue by Ishaanhike** [SvanBoxel/delete-merged-branch#29]
Use case: 

Other than feature branches, I have multiple release branches which time to time merge into master.

Though it will be great to have the feature branches deleted automatically, is it possible to exempt certain branches?

**Comment by SvanBoxel** [comment]
I agree @Ishaanhike, this should be possible. I'm a bit short on time at the moment, but keep an 👁 on this project!

**Comment by tplk** [comment]
I made similar app, it's quite easy to implement.
https://github.com/tplk/delete-branch-after-pr-merge/blob/master/src/index.js#L30
I'll create a pr if I have some spare time.

**Comment by Ishaanhike** [comment]
> I made similar app, it's quite easy to implement.
> https://github.com/tplk/delete-branch-after-pr-merge/blob/master/src/index.js#L30
> I'll create a pr if I have some spare time.

@tplk if I want to use it, how do I mention the branch names to be excluded?

**Comment by Ishaanhike** [comment]
@SvanBoxel Just a suggestion, if we can have this flow - mention excluded branches in config.yml and they get excluded on "branch deletion process post merge"

**Comment by berthamilton** [comment]
I'm also interested in this. Any news on when you might have a chance to look into it?

**Comment by tplk** [comment]
@Ishaanhike no it won't, it compares branch names as strings.

**Comment by Ishaanhike** [comment]
> @Ishaanhike no it won't, it compares branch names as strings.

Thanks @tplk , I know its a bit too much to ask for this, if possible please help though. Will solve a huge problem for lot us.
Appreciate for your support :)

**Comment by SvanBoxel** [comment]
@Ishaanhike Go ahead and open a new issue. I'll take a look at it.
