### ISSUE TITLE
Consider publishing as npm module

### ISSUE THREAD

**Issue by Graham42** [SvanBoxel/delete-merged-branch#55]
To use this github app with `@probot/serverless-lambda` or `@probot/serverless-gcf` would be useful to have this app available as an npm package. Then can do something like

```js
const serverless = require('@probot/serverless-lambda')
const appFn = require('delete-merged-branch')
module.exports.probot = serverless(appFn)
```

Would you consider publishing this as an npm module?

**Comment by SvanBoxel** [comment]
Great suggestion @Graham42. Let's make it happen.

**Comment by SvanBoxel** [comment]
Hereyago: https://www.npmjs.com/package/delete-merged-branch ✌️
