### ISSUE TITLE
[bug] GitHub Action hanging

### ISSUE THREAD

**Issue by matthewnessworthy** [SvanBoxel/delete-merged-branch#75]
The github action doesn't appear to work. I've cancelled a couple of tasks after 15min of activity and the logs show the following after getting everything setup

```
...
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
14:35:13.811Z  INFO probot: Listening on http://localhost:3000
14:35:13.814Z  INFO probot:
  
  Welcome to Probot! Go to http://localhost:3000 to get started.
```

**Comment by SvanBoxel** [comment]
@matthewnessworthy Is this still happening? I'm not able to replicate it.

**Comment by rtimush** [comment]
@SvanBoxel Happens for me as well with the same logs as above

**Comment by mkj28** [comment]
Yeah same here, I cancelled the action after 40+ minutes. Tail of the log is :
```
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
21:56:20.971Z  INFO probot: Listening on http://localhost:3000
21:56:20.973Z  INFO probot:
  
  Welcome to Probot! Go to http://localhost:3000 to get started.
```

**Comment by mkj28** [comment]
@matthewnessworthy / @rtimush were you ever able to figure out how to make it work?

**Comment by matthewnessworthy** [comment]
@mkj28 never got it to work for me

**Comment by rtimush** [comment]
@mkj28 me neither, I switched to an alternative action that is broken in a different way :)

**Comment by mkj28** [comment]
> @mkj28 me neither, I switched to an alternative action that is broken in a different way :)

great! :(
