### ISSUE TITLE
[feature-request] Setting to only delete for certain commiters

### ISSUE THREAD

**Issue by Minipada** [SvanBoxel/delete-merged-branch#8]
First, thanks for the work, it looks amazing!

In my organization, I would be interested in it but not all members are. Could there be a setting to choose for whom it is enabled?

**Comment by SvanBoxel** [comment]
@Minipada Missed your issue, sorry for the late response! Could you tell me in more detail how this would - ideally - look for you? Do you want a configuration file? Do you want it to be based on tin which github-team someone is. Anything else? Thanks!

**Comment by Minipada** [comment]
Hey @SvanBoxel , thanks for the answer :).
I was wondering, could we use your .env file so it stays as simple as it is now? It would be an optional parameters to pass github users/team

**Comment by SvanBoxel** [comment]
I assume you're not committing your .env file to GH because most of the time it contains sensitive information. So that's not a viable option for most people.

**Comment by SvanBoxel** [comment]
Okay, let me dive into it this weekend. 🌮

**Comment by SvanBoxel** [comment]
Closing this feature request as it won't be implemented anytime soon. (Feel free to open a pr yourself if you want to see this functionality added)
