### ISSUE TITLE
GItHub: Automatically delete head branches of pull requests

### ISSUE THREAD

**Issue by zoispag** [SvanBoxel/delete-merged-branch#92]
Looks like the simplest use case is now covered by github. I thought to let you know!
In any case thanks for this great bot. A pleasure to use so far!

[Blog post](https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/)

Automatically delete head branches of pull requests
Repositories can now be set to delete the head branch of a pull request once it has merged into the base branch.

[Learn more about automatic deletion of branches on GitHub](https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches)

**Comment by SvanBoxel** [comment]
Yes, great!

**Comment by SvanBoxel** [comment]
I've added a note to the readme.
